### ISSUE TITLE
Fix rows duplication in the history tables

### ISSUE THREAD

**Issue by pseveryn** [gcp-pdp/geo-openstreetmap#20]
Redirected from #17

`history_ways` contains duplications of version=2. Need to check how it happened
`SELECT * FROM bigquery-public-data.geo_openstreetmap.history_ways WHERE id=9820303 AND version=2`

**Comment by pseveryn** [comment]
Fixed. This problem came from previous runs of history file processing

**Comment by allenday** [comment]
do you need to do a full reprocessing?

**Comment by allenday** [comment]
@nanodan would be great if you can help do more QA

**Comment by pseveryn** [comment]
@allenday no need. We've recovered data from the backup dataset. For now, `bigquery-public-data:geo_openstreetmap.history_*` tables are up to date
