### ISSUE TITLE
Tables in BQ not updated Since Nov 23 2020

### ISSUE THREAD

**Issue by nanodan** [gcp-pdp/geo-openstreetmap#29]

**Comment by nanodan** [comment]
Discrepancies in update dates:

history_changesets: Last modified	Dec 10, 2019, 5:30:52 PM
history_layers: Last modified Nov 16, 2020, 4:50:57 AM
history_nodes: Last modified Nov 23, 2020, 1:11:44 AM
history_relations: Last modified Nov 23, 2020, 1:11:16 AM
history_ways: Last modified Nov 23, 2020, 1:11:36 AM
planet_layers: Last modified Dec 28, 2020, 12:51:48 AM
planet_nodes: Last modified Dec 28, 2020, 12:54:21 AM

It seems like the history tables are out of date and out of sync with the planet tables.

**Comment by obsh** [comment]
Thank you, we'll check ASAP.

**Comment by obsh** [comment]
We have an issue in the history file import pipeline. Working on the fix.

**Comment by nanodan** [comment]
Since I believe you are also using Airflow, some of our relevant checks are included below. We are right now doing a monthly update of our reference map at the beginning of the month with a reference as the prior month. Since the tables should be updating bi-weekly, this should always return some count greater than zero as OSM itself sees changes every day. In the pipeline whatever the cadence is this could just be changed from a date_trunc to checking that days partition for all tables to see if the records are current. For us we are checking to see if there are any osm_timestamp records in the history for that day of the previous month. We build a "snapshot" of OSM based on the date of interest from the history tables. We are also working to get a BQ ARIMA model set up for volume monitoring and alerts as the history tables should be growing over time.

        check_retires = 3
        check_retry_delay = datetime.timedelta(minutes=30)

        check_osm_way = BigQueryCheckOperator(
            task_id='check_osm_way',
            use_legacy_sql=False,
            retries=check_retires,
            retry_delay=check_retry_delay,
            sql="SELECT COUNT(*) FROM `bigquery-public-data.geo_openstreetmap.history_ways` WHERE DATE(osm_timestamp) = Date_Trunc('{{ds}}',MONTH)",  # noqa: E501
        )

        check_osm_node = BigQueryCheckOperator(
            task_id='check_osm_node',
            use_legacy_sql=False,
            retries=check_retires,
            retry_delay=check_retry_delay,
            sql="SELECT COUNT(*) FROM  `bigquery-public-data.geo_openstreetmap.history_nodes` WHERE DATE(osm_timestamp) = Date_Trunc('{{ds}}',MONTH)",  # noqa: E501
        )

**Comment by obsh** [comment]
Hi @nanodan, thank you for sharing checks!
I'll test it and incorporate into the pipeline.

By the way we have history pipeline import  just finished successfully. Currently, data is up to date in history tables.
Turned out it was a problem with not enough resources available for the pipeline.

Also, to have more visibility we plan to incorporate the badge with last import date and status into the repository's README.

**Comment by nanodan** [comment]
@obsh Thanks, we've updated our tables. It looks like the fix started introducing some duplicates. I'll open a separate issue for that.

**Comment by ericrwolfe** [comment]
@obsh Do you know if there's a new issue with the OSM update pipeline?

The `geo_openstreetmap.history_*` tables look up to date (last updated Jun 14), but the `geo_openstreetmap.planet_*` tables haven't been updated since May 03.
